name: CI/CD - Terraform

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ "main", "staging" ]

permissions:
  contents: read
  id-token: write   # required for OIDC
  issues: write
  pull-requests: write

env:
  TF_VERSION: 1.13.2
  TFLINT_VERSION: 0.45.0
  TFSEC_VERSION: 1.33.0
  CHECKOV_VERSION: 2.0.0

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    name: CI checks (format, lint, security)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup tflint
        run: |
          curl -sSL "https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
          unzip tflint.zip && sudo mv tflint /usr/local/bin
          tflint --version
      
      - name: Terraform fmt check
        run: |
          cd infra
          terraform fmt -check
      
